### PR TITLE
Use ^2.1@dev as version constraint of sulu/sulu package

### PR DESCRIPTION
**Pull request by nnatter**
Downside of this is that we have to remember it and change it each time a minor version is release 🤔

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@nnatter `^2.1@dev` will also install `^2.2@dev` so the `^` works the same here. Else you would need to use `2.1.*@dev`  or `~2.1.0@dev`

**Comment by nnatter** [comment]
@alexander-schranz Should we just use `^2.0@dev` then?

**Comment by alexander-schranz** [comment]
@nnatter we need specify the lowest version correctly and thats `^2.1@dev` if we specify `^2.0@dev` it basically allow to install `2.0.0-alpha-1` (because thats the lowest dev version of 2.0.0).

**Comment by nnatter** [comment]
@alexander-schranz okay but then this means we have to update it when we release `2.1` right? 🙈

**Comment by alexander-schranz** [comment]
@nnatter yes to set the required min version, but we also need to update the branch aliases as we use `release/*` branch names.

**Comment by danrot** [comment]
And when releasing I usually adapt the `sulu/sulu` version anyway, so it shouldn't be such a big deal :slightly_smiling_face: @alexander-schranz Can you merge if this is ok for you?

**Pull request merged**
